### ISSUE TITLE
AnimeBack Support

### ISSUE THREAD

**Issue by LeGitHubDeTai** [LeGitHubDeTai/AnimeBack#1]
vous pouvez proposez vos idée d'ajout ou même reporter un bug sur le serveur discord suivant : [Discord](https://discord.gg/yCAymfAVTh) ou grâce aux issues

you can propose your idea to add or even report a bug on the following discord server:  [Discord](https://discord.gg/yCAymfAVTh) or thanks to the exits

**Comment by How2benoob** [comment]
The Discord invite is currently invalid. Could you update it to a working link?

**Comment by LeGitHubDeTai** [comment]
hello, here is the link to the animeback discord: https://discord.com/invite/zctFdAPUzP
