### ISSUE TITLE
Bottom right portion of the screen disabled

### ISSUE THREAD

**Issue by sammypanda** [LeGitHubDeTai/AnimeBack#3]
**Describe the bug**
When animeback is running, any window that is over the area in the bottom right for the watermark is unusable (except taskbar interactions)

**To Reproduce**
1. Open any windowed application (good example is the scroll bar in a browser)
2. Try to use the area of the screen where the watermark is
3. See none of the clicks registering on the application

**Expected behavior**
Should be able to have mouse clicks register over the area where the watermark is in the background

**Screenshots**
![The area above the taskbar on the bottom right of the screen that has been disabled by animeback](https://user-images.githubusercontent.com/38725335/113495586-2f57fc00-9536-11eb-9c3e-a833350ae380.PNG)

**Desktop**
 - OS: Windows

**Browser**
 - DeGoogled Chromium v88.0.4324.182 [Dev Build]

**Comment by LeGitHubDeTai** [comment]
![image](https://user-images.githubusercontent.com/65470169/113504449-70e9a680-9538-11eb-9a08-e745076a6360.png)

hello, i will correct this problem, what is your version of animeback?

**Comment by sammypanda** [comment]
7.0.3 :)
![version 7.0.3](https://user-images.githubusercontent.com/38725335/113522964-26276780-95e8-11eb-9f93-54e67f2989ae.png)

**Comment by LeGitHubDeTai** [comment]
fix in 7.0.4 !
