### ISSUE TITLE
Cannot read property 'webContents' of null

### ISSUE THREAD

**Issue by sammypanda** [LeGitHubDeTai/AnimeBack#4]
**Bug Description**
When trying to load one of the preset wallpapers, it errors out

**To Reproduce**
1. Open AnimeBack
2. Click on one of the (not local) wallpapers
3. See error

**Expected Behavior**
Fetch and change the wallpaper without an error

**Screenshots**
![image](https://user-images.githubusercontent.com/38725335/114005062-8cd7aa00-98a2-11eb-9323-b120e50361ae.png)

**Desktop**
 - OS: Windows
 - AnimeBack Version: 7.0.7

**Additional Context**
- Exiting and pressing okay does not exit the error, indicating that the error is in a loop. It can only be fixed by killing the AnimeBack process.
- When AnimeBack is opened again, the wallpaper has changed to the intended wallpaper

**Comment by LeGitHubDeTai** [comment]
hello, thanks for reporting this error!

please send me the log file in this directory ``%appdata%/Roaming/AnimeBack/logs``
![image](https://user-images.githubusercontent.com/65470169/114011336-65162100-9865-11eb-887a-8e3e4a84bc09.png)

**Comment by sammypanda** [comment]
[main.log](https://github.com/LeGitHubDeTai/AnimeBack/files/6278290/main.log)

**Comment by LeGitHubDeTai** [comment]
I tried to solve the problem I leave the issue open if you have the error again let me know <3

ps: when the premium version comes out I will give you 1 month for the bugs you found!

**Comment by sammypanda** [comment]
> 
> 
> I tried to solve the problem I leave the issue open if you have the error again let me know <3
> 
> ps: when the premium version comes out I will give you 1 month for the bugs you found!

awww thank you puddin (^^) :heart::sparkles:

**Comment by sammypanda** [comment]
inactive
