### ISSUE TITLE
AnimeBack using 75% of CPU

### ISSUE THREAD

**Issue by How2benoob** [LeGitHubDeTai/AnimeBack#9]
For some reason, shortly after I installed the program and chose a background, my CPU fan began ramping up, and when I open up task manager to find the cause, AnimeBack was running at 75% CPU usage

The software is running at version 7.2.2
My hardware is the following:
i5-3570k 4c4t @ 3.9Ghz
24gb DDR3 1600mhz
Radeon RX 470 4gb
Dual Monitors, one being 1080x1920@66hz, and the other being 1440x900@75hz

As this is a relatively fresh install of windows, I can't think of any other programs that may cause issues.

EDIT: Relaunching fixes the issue
![cpuusage2](https://user-images.githubusercontent.com/53295422/116331584-b7c46800-a795-11eb-9f47-71bd10d44913.png)
![cpuusage](https://user-images.githubusercontent.com/53295422/116332410-500f1c80-a797-11eb-8975-039e5f01273e.png)

**Comment by How2benoob** [comment]
En français pour votre commodité :

Pour une raison quelconque, peu de temps après avoir installé le programme et choisi un arrière-plan, le ventilateur de mon processeur a commencé à monter en régime, et lorsque j'ai ouvert le gestionnaire des tâches pour en trouver la cause, AnimeBack fonctionnait à 75 % de l'utilisation du processeur.

Le logiciel fonctionne avec la version 7.2.2.
Mon matériel est le suivant
i5-3570k 4c4t @ 3.9Ghz
24gb DDR3 1600
Radeon RX 470 4gb
Deux moniteurs, l'un étant 1080x1920@66hz, et l'autre étant 1440x900@75hz.

Comme il s'agit d'une installation relativement récente de Windows, je ne vois pas d'autres programmes susceptibles de causer des problèmes.
![cpuusage2](https://user-images.githubusercontent.com/53295422/116331584-b7c46800-a795-11eb-9f47-71bd10d44913.png)
![cpuusage](https://user-images.githubusercontent.com/53295422/116332410-500f1c80-a797-11eb-8975-039e5f01273e.png)

**Comment by LeGitHubDeTai** [comment]
thanks for the postponement and sorry for the problem encountered during use.
